-- Classificados, etapa 3: planos e assinatura do lojista.
--
-- Migration apenas aditiva: cria duas tabelas e cinco funções. Nenhuma
-- tabela existente é alterada e nenhuma regra de visibilidade muda aqui.
-- A pausa da loja e dos anúncios ao fim da assinatura entra na etapa 7.
--
-- Regras de negócio:
--   * plano gratuito: 5 anúncios a cada 30 dias, cada anúncio vale 60 dias,
--     sem edição;
--   * plano lojista: mensal, sem limite, sem vencimento, com edição;
--   * a assinatura é ativada manualmente pelo administrador;
--   * ao terminar, a loja entra em carência por 15 dias e depois expira.

-- ---------------------------------------------------------------------
-- PLANOS
-- ---------------------------------------------------------------------

create table public.planos (
  id smallint generated by default as identity primary key,
  codigo text not null unique,
  nome text not null,
  descricao text,
  preco_mensal numeric(10, 2),
  limite_anuncios_ciclo integer,
  dias_ciclo integer,
  dias_validade_anuncio integer,
  permite_editar_anuncio boolean not null default false,
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),

  constraint planos_codigo_check
    check (codigo in ('gratuito', 'lojista')),
  constraint planos_nome_check
    check (char_length(trim(nome)) between 1 and 60),
  constraint planos_preco_check
    check (preco_mensal is null or preco_mensal >= 0),
  constraint planos_limite_check
    check (limite_anuncios_ciclo is null or limite_anuncios_ciclo > 0),
  constraint planos_ciclo_check
    check (dias_ciclo is null or dias_ciclo > 0),
  constraint planos_validade_check
    check (dias_validade_anuncio is null or dias_validade_anuncio > 0)
);

comment on table public.planos is
  'Classificados: regras de cada plano de anúncio. Limites nulos significam sem limite.';

insert into public.planos (
  codigo, nome, descricao, preco_mensal,
  limite_anuncios_ciclo, dias_ciclo, dias_validade_anuncio,
  permite_editar_anuncio
) values
  (
    'gratuito',
    'Gratuito',
    'Para quem quer anunciar de vez em quando.',
    0,
    5, 30, 60,
    false
  ),
  (
    'lojista',
    'Lojista',
    'Para lojas que anunciam sempre.',
    null,
    null, null, null,
    true
  );

alter table public.planos enable row level security;

create policy planos_leitura_publica
  on public.planos
  for select
  to anon, authenticated
  using (ativo = true);

revoke all on table public.planos from anon, authenticated;
grant select on table public.planos to anon, authenticated;

-- ---------------------------------------------------------------------
-- ASSINATURAS
-- ---------------------------------------------------------------------
-- Cada ativação ou renovação gera um período. O histórico nunca é apagado.

create table public.assinaturas (
  id uuid primary key default gen_random_uuid(),
  loja_id uuid not null references public.lojas (id) on delete cascade,
  plano_id smallint not null references public.planos (id),
  inicio_em timestamptz not null default now(),
  fim_em timestamptz not null,
  encerrada_em timestamptz,
  ativada_por uuid references public.profiles (id) on delete set null,
  encerrada_por uuid references public.profiles (id) on delete set null,
  motivo_encerramento text,
  criado_em timestamptz not null default now(),

  constraint assinaturas_periodo_check
    check (fim_em > inicio_em),
  constraint assinaturas_motivo_check
    check (
      motivo_encerramento is null
      or char_length(trim(motivo_encerramento)) between 1 and 500
    )
);

comment on table public.assinaturas is
  'Classificados: períodos de assinatura das lojas, ativados manualmente pelo administrador.';

create index assinaturas_loja_fim_idx
  on public.assinaturas (loja_id, fim_em desc);
create index assinaturas_plano_idx
  on public.assinaturas (plano_id);
create index assinaturas_ativada_por_idx
  on public.assinaturas (ativada_por);
create index assinaturas_encerrada_por_idx
  on public.assinaturas (encerrada_por);

alter table public.assinaturas enable row level security;

-- Leitura: o dono da loja e o administrador. Escrita só pelas funções abaixo.
create policy assinaturas_leitura_dono_ou_admin
  on public.assinaturas
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.lojas l
      where l.id = assinaturas.loja_id
        and l.proprietario_id = (select auth.uid())
    )
    or (select public.sou_admin())
  );

revoke all on table public.assinaturas from anon, authenticated;
grant select on table public.assinaturas to authenticated;

-- ---------------------------------------------------------------------
-- SITUAÇÃO DA ASSINATURA
-- ---------------------------------------------------------------------
-- Fim efetivo: o menor entre o fim contratado e o encerramento antecipado.
--   ativa          -> ainda dentro do período
--   carencia       -> terminou há até 15 dias (loja pausada, anúncios no ar)
--   expirada       -> terminou há mais de 15 dias (anúncios pausados)
--   sem_assinatura -> a loja nunca assinou

create or replace function private.situacao_assinatura(p_loja_id uuid)
returns table (
  situacao text,
  inicio_em timestamptz,
  fim_em timestamptz,
  carencia_ate timestamptz
)
language sql
stable
security definer
set search_path = ''
as $$
  with periodos as (
    select
      a.inicio_em,
      least(a.fim_em, coalesce(a.encerrada_em, a.fim_em)) as fim_efetivo
    from public.assinaturas a
    where a.loja_id = p_loja_id
  ),
  resumo as (
    select
      min(p.inicio_em) filter (where p.fim_efetivo > now()) as inicio_vigente,
      max(p.fim_efetivo) as fim_efetivo
    from periodos p
  )
  select
    case
      when r.fim_efetivo is null then 'sem_assinatura'
      when r.fim_efetivo > now() then 'ativa'
      when r.fim_efetivo + interval '15 days' > now() then 'carencia'
      else 'expirada'
    end,
    r.inicio_vigente,
    r.fim_efetivo,
    r.fim_efetivo + interval '15 days'
  from resumo r;
$$;

revoke all on function private.situacao_assinatura(uuid)
  from public, anon, authenticated;

-- ---------------------------------------------------------------------
-- LOJISTA: MINHA ASSINATURA
-- ---------------------------------------------------------------------

create or replace function public.minha_assinatura()
returns table (
  loja_id uuid,
  loja_nome text,
  situacao text,
  inicio_em timestamptz,
  fim_em timestamptz,
  carencia_ate timestamptz
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    l.id,
    l.nome::text,
    s.situacao,
    s.inicio_em,
    s.fim_em,
    s.carencia_ate
  from public.lojas l
  cross join lateral private.situacao_assinatura(l.id) s
  where l.proprietario_id = (select auth.uid())
  order by l.criado_em;
$$;

revoke all on function public.minha_assinatura() from public, anon;
grant execute on function public.minha_assinatura() to authenticated;

-- ---------------------------------------------------------------------
-- ADMIN: LISTAR, ATIVAR E ENCERRAR
-- ---------------------------------------------------------------------

create or replace function public.listar_assinaturas_admin()
returns table (
  loja_id uuid,
  situacao text,
  inicio_em timestamptz,
  fim_em timestamptz,
  carencia_ate timestamptz
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if (select auth.uid()) is null
     or not public._usuario_e_admin((select auth.uid())) then
    raise exception 'Acesso restrito a administradores.';
  end if;

  return query
  select
    l.id,
    s.situacao,
    s.inicio_em,
    s.fim_em,
    s.carencia_ate
  from public.lojas l
  cross join lateral private.situacao_assinatura(l.id) s;
end;
$$;

revoke all on function public.listar_assinaturas_admin() from public, anon;
grant execute on function public.listar_assinaturas_admin() to authenticated;

-- Ativa ou renova. Se já houver período vigente, o novo começa onde ele
-- termina, para o lojista não perder dias ao renovar antes do fim.
create or replace function public.ativar_assinatura_loja_admin(
  p_loja_id uuid,
  p_meses integer default 1
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := (select auth.uid());
  v_loja public.lojas%rowtype;
  v_plano_id smallint;
  v_inicio timestamptz;
  v_fim timestamptz;
  v_fim_atual timestamptz;
begin
  if v_uid is null or not public._usuario_e_admin(v_uid) then
    raise exception 'Acesso restrito a administradores.';
  end if;

  if p_meses is null or p_meses < 1 or p_meses > 12 then
    raise exception 'Informe de 1 a 12 meses.';
  end if;

  select *
  into v_loja
  from public.lojas
  where id = p_loja_id
  for update;

  if not found then
    raise exception 'Loja não encontrada.';
  end if;

  if v_loja.status_aprovacao <> 'aprovada' then
    raise exception 'Só é possível ativar a assinatura de uma loja aprovada.';
  end if;

  select p.id
  into v_plano_id
  from public.planos p
  where p.codigo = 'lojista'
    and p.ativo = true;

  if v_plano_id is null then
    raise exception 'O plano de lojista não está disponível.';
  end if;

  select s.fim_em
  into v_fim_atual
  from private.situacao_assinatura(p_loja_id) s
  where s.situacao = 'ativa';

  v_inicio := coalesce(v_fim_atual, now());
  v_fim := v_inicio + make_interval(months => p_meses);

  insert into public.assinaturas (
    loja_id, plano_id, inicio_em, fim_em, ativada_por
  ) values (
    p_loja_id, v_plano_id, v_inicio, v_fim, v_uid
  );

  perform private.salvar_notificacao(
    v_loja.proprietario_id,
    'loja_status',
    'Assinatura ativa',
    'A assinatura da loja ' || v_loja.nome || ' está ativa até '
      || to_char(v_fim at time zone 'America/Sao_Paulo', 'DD/MM/YYYY') || '.',
    'painel-loja.html',
    jsonb_build_object('loja_id', p_loja_id, 'assinatura_fim', v_fim),
    'assinatura_ativa:' || p_loja_id::text,
    true
  );

  return jsonb_build_object(
    'loja_id', p_loja_id,
    'situacao', 'ativa',
    'inicio_em', v_inicio,
    'fim_em', v_fim
  );
end;
$$;

revoke all on function public.ativar_assinatura_loja_admin(uuid, integer)
  from public, anon;
grant execute on function public.ativar_assinatura_loja_admin(uuid, integer)
  to authenticated;

-- Encerra agora todos os períodos ainda vigentes ou futuros da loja.
create or replace function public.encerrar_assinatura_loja_admin(
  p_loja_id uuid,
  p_motivo text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := (select auth.uid());
  v_motivo text := nullif(trim(coalesce(p_motivo, '')), '');
  v_loja public.lojas%rowtype;
  v_encerrados integer;
begin
  if v_uid is null or not public._usuario_e_admin(v_uid) then
    raise exception 'Acesso restrito a administradores.';
  end if;

  if v_motivo is not null and char_length(v_motivo) > 500 then
    raise exception 'O motivo deve ter no máximo 500 caracteres.';
  end if;

  select *
  into v_loja
  from public.lojas
  where id = p_loja_id
  for update;

  if not found then
    raise exception 'Loja não encontrada.';
  end if;

  update public.assinaturas a
  set
    encerrada_em = now(),
    encerrada_por = v_uid,
    motivo_encerramento = v_motivo
  where a.loja_id = p_loja_id
    and a.encerrada_em is null
    and a.fim_em > now();

  get diagnostics v_encerrados = row_count;

  if v_encerrados = 0 then
    raise exception 'Esta loja não tem assinatura ativa.';
  end if;

  perform private.salvar_notificacao(
    v_loja.proprietario_id,
    'loja_status',
    'Assinatura encerrada',
    'A assinatura da loja ' || v_loja.nome
      || ' foi encerrada. Os anúncios continuam no ar por mais 15 dias.',
    'painel-loja.html',
    jsonb_build_object('loja_id', p_loja_id),
    'assinatura_encerrada:' || p_loja_id::text,
    true
  );

  return jsonb_build_object(
    'loja_id', p_loja_id,
    'situacao', 'carencia',
    'periodos_encerrados', v_encerrados
  );
end;
$$;

revoke all on function public.encerrar_assinatura_loja_admin(uuid, text)
  from public, anon;
grant execute on function public.encerrar_assinatura_loja_admin(uuid, text)
  to authenticated;
